spring:
  cloud:
    gateway:
      routes:
      - id: msvc-products
        uri: lb://msvc-products
        predicates:
        - Path=/msvc/products/**
        filters:
        - StripPrefix=2
        - name: Sample
          args:
            name: user
            value: Cesar
            message: mensaje personalizado para productos
      - id: msvc-items
        uri: lb://msvc-items
        predicates:
        - Path=/msvc/items/**
        filters:
        - StripPrefix=2