spring:
  cloud:
    gateway:
      routes:
      - id: msvc-products
        uri: lb://msvc-products
        predicates:
        - Path=/msvc/products/**
        filters:
        - StripPrefix=2
      - id: msvc-items
        uri: lb://msvc-items
        predicates:
        - Path=/msvc/items/**
        filters:
        - StripPrefix=2